/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmailType { 
    id: string | null;
    experianceDays?: number | null;
    emailTitle: string | null;
    intersectDepartmentIds?: Array<number> | null;
    exceptDepartmentIds?: Array<number> | null;
    intersectOrganizationNames?: Array<string> | null;
    bodyName: string | null;
    intersectTowns?: Array<string> | null;
    exceptTowns?: Array<string> | null;
    dontSendAfterDate?: Date | null;
    maternityDays?: number | null;
    forGenders?: Array<string> | null;
    dayCountsForResend?: number | null;
    intersectUserPosts?: Set<string> | null;
    exceptUserPosts?: Set<string> | null;
    senderEmail: string | null;
    bcc?: Array<string> | null;
}

